### ISSUE TITLE
websiteにスタイルを適用

### ISSUE THREAD

**Issue by kmikage** [kmikage/yokai-password#17]
#16 で、`index.html` へのCSS適用を頂いているので、mergeに向けて対応。

**Comment by kmikage** [comment]
修正が必要な箇所
- ファイル名 ( index.html -> index.utf8.html )
- 文字コードの指定の削除
- （できれば）CSSは外部ファイルにして、@importになると嬉しい

ここまでの経緯
- レンタルサーバー(XREA FreePlan)では、広告表示の兼ね合いでSJISでのアップロードが必須だった
- 実際の制作そのものは、UTF-8で行い、アップロード用のスクリプト内で文字コードを変換していた
- そのため、オリジナルのファイル名は、 `index.utf8.html` となっていた
- websiteは誰も触らないと思い、手を抜いていた 笑

**Comment by pklion** [comment]
対応ありがとうございます。
修正の件について、了解です。
Githubの扱いにいまだ慣れていないので、変な操作などしてしまったらすみません…
CSSは別ファイルにして良いか分からなかったのでインラインにしておりました
すぐに変更しますね

**Comment by pklion** [comment]
すみません… `issue/17` のブランチにcommitできないです…(アクセス許可がないのか、はたまた私の操作が間違っているのか…)
もし良ければ方法をご教授ください
(環境はGithub Desktop on Windows 11です)

**Comment by kmikage** [comment]
@pklion 
了解です、修正よろしくお願いします。

GitHubについては、みんな通る道ですので 笑
のんびりいきましょうー

僕も明日・明後日と用事が重なっているので、レス遅くなるかも知れません。

**Comment by kmikage** [comment]
@pklion 

> issue/17 のブランチにcommitできないです…
pklionさんのリポジトリにcommit, pushした後、先と同じようにPullRequestして下さいです。
先のPRでは、mainに対してのPRでしたが、issues/17宛にPRいただければ。

**Comment by pklion** [comment]
あ、なるほど。
了解しました。

**Comment by pklion** [comment]
PR作成させていただきました。
Contributors の欄に抽出の方々を入れるのもアリだな、と思いつつリストがないので迷っているところです…いかがいたしましょう？

**Comment by kmikage** [comment]
@pklion 
PR #18 ですが、以下のコミットまででPRし直して頂けませんか？
https://github.com/kmikage/yokai-password/pull/18/commits/33b553c106421dec58db8577e59979b6a5156253

以降のコミットなのですが、mergeの前に、一度お話をする必要があるかと思います。
DiscordでDMさせて頂きますね。

**Comment by pklion** [comment]
Revert してみたのですが如何でしょう？

**Comment by kmikage** [comment]
サイトの修正は、以上で終わり。
アップロード用のツール（非公開）を修正します。

**Comment by kmikage** [comment]
#24  で取り込みました。
