### ISSUE TITLE
ホームページに目次をつける

### ISSUE THREAD

**Issue by pklion** [kmikage/yokai-password#27]
それなりに長いページなので、目次を表示したい (スマホで見た時だけ、というのもありかもしれないです)

**Comment by kmikage** [comment]
#32 とも重複するので、まとめてになりますが。
もともとこのサイトを作った経緯が、「passwords.zipが大きすぎて、配布しようにもGitHubに置けなくなったので、配布ページつくった（要には、ただのストレージ代わりｗ）」だったりします。

なので、ここのviewに力を入れて頂くよりは、 kazuhito_mさんところのサイトの内容を整理して頂くほうがありがたいのかなー、と思います。

Discord Serverの サイト編集部屋で、このあたりのお話ができたら、スムーズかと思います

- https://youkaiosugi.com/overview
- https://youkaiosugi.com/infomation

**Comment by pklion** [comment]
一旦closeします
