### ISSUE TITLE
コントリビューターリストを更新

### ISSUE THREAD

**Issue by pklion** [kmikage/yokai-password#30]
README.md とホームページのコントリビューターリストがそれぞれ違うので双方をmergeする
mdをmarkdown-wasmとかで読み込むのもありかと思いますがJS書いたことない…

**Comment by kmikage** [comment]
コントリビューターの整理は、必要かなー、と思ってました。
ざっくり、以下に分けられるかと思います。

- パスワード解析されてた方々
- ハズレパスワードの検索をされてる方々
- yokai-passwordsに協力いただいた方々

1つめ、2つめは、originalのディレクトリの中身を観たらわかると思うのです。
3つめに関しては、僕の方がわかると思うので、明日にでもまとめておきます。

**Comment by pklion** [comment]
こんな感じでしょうかね
コントリビュータ－
------------------

### 運営協力（順不同）

- [@Imaha486](https://twitter.com/Imaha486)
- crus\_m\#6673
- [@kazuhito\_m](https://twitter.com/kazuhito_m)
- [@kei9298p](https://twitter.com/kei9298p)
- tanzaku\#2547

### パスワード解析（順不同）

- [@0x7FF](https://twitter.com/0x7FF)
- [@A\_SixSquare](https://twitter.com/A_SixSquare)
- [@Imaha486](https://twitter.com/Imaha486)
- [@K\_Satori](https://twitter.com/K_Satori)
- Luzuly\#1295
- [@Riku_2004](https://twitter.com/Riku_2004) = お餅のkerohira\#6792
- [@UnBrkblCrbn](https://twitter.com/UnBrkblCrbn)
- YH\#8655
- [@Yu\_Ti\_S6](https://twitter.com/Yu_Ti_S6)
- botesan\#8880
- [@command774](https://twitter.com/command774)
- crus_m\#6673
- [@fuyuduki](https://twitter.com/fuyuduki)
- kagura1050#2269
- [@kuu\_00013](https://twitter.com/kuu_00013)
- [@obaky](https://twitter.com/obaky)
- over80\#4563
- [@taka\_hvc1](https://twitter.com/taka_hvc1)
- tanzaku\#2547
- いぷしろん\#8693
- 冠者(KJ)\#8273
- 赤白園\#9838

### ハズレパスワード解析（順不同）

- [@Imaha486](https://twitter.com/Imaha486)
- Luzuly\#1295
- botesan\#8880
- over80\#4563
- 西園寺公望\#1400

### その他（順不同） (WIP)

#### サイト運営
- yokaiosugi.com
- yokai.ddns.net

**Comment by kmikage** [comment]
Tintwitter含めて調べ直していただいたんですね。
めっちゃ、ありがたいですっ 涙

**Comment by kmikage** [comment]
@pklion 
いったん、`README.md` でまとめ直してみました。
https://github.com/kmikage/yokai-password/blob/issues/30/README.md

README.mdが固まったら、これをベースに他を直していきたいです。

**Comment by pklion** [comment]
README.md 拝見しました。
基本的には大丈夫かと思います。
ただ、kerohiraさんの名前については[メッセージ](https://discord.com/channels/924501371963736085/927074399264325632/927080884279070721)を元にどちらを書かせていただくか確認したほうが良いかと思いますが、如何でしょう？

**Comment by kmikage** [comment]
> こーのいけさん、あーすまんさんがいらっしゃらないかと

えっと、もともとリストアップされてなかった方です？？
twitter上の解析は、kazuhito_mさんがタグを頼りに探してくださってたので、あーすまんさんの例では漏れてるかもです。。
該当のtweetのURLがあれば、mergeするので、教えて頂けると幸いですっ

> kerohiraさんの名前については
> メッセージを元にどちらを書かせていただくか確認したほうが良いかと思いますが、如何でしょう？

これだけだとよくわからないのですが、
Discord上のお名前と、twitter上のお名前が違う、という意味です？？

**Comment by pklion** [comment]
> えっと、もともとリストアップされてなかった方です？？ twitter上の解析は、kazuhito_mさんがタグを頼りに探してくださってたので、あーすまんさんの例では漏れてるかもです。。 該当のtweetのURLがあれば、mergeするので、教えて頂けると幸いですっ
あっ、そういうことなのですね。選考基準が分かっていなかったのでDiscordなど他のサイト見ながら考えていた感じです。この点についての編集は今のところ不要かと思います
> これだけだとよくわからないのですが、 Discord上のお名前と、twitter上のお名前が違う、という意味です？？
これについては、御本人が@Riku_2004さんとしての掲載をご希望されているのかと思いまして…(私の読み間違いでしたらすみません)

**Comment by kmikage** [comment]
了解ですー
リストアップの順番は、現状こんな感じにしてます。
何かいい感じの方法があれば、教えて欲しいです

## 名前の優先順位
 - Discord上で提供があった場合 -> Discord上でのお名前
 - Twitter上で、こちらから見つけた場合 -> Twitter上でのお名前

## リストアップの順序（現状）
 - Discordアカウントしかわからない方（リンク先なし）
 - Discordアカウントが主で、リンク先がわかる方（Twitter, GitHubなど）
 - Discord意外が主で、リンク先のわかる方
 - 自分(kmikage / kei9298p)

**Comment by pklion** [comment]
> 了解ですー リストアップの順番は、現状こんな感じにしてます。 何かいい感じの方法があれば、教えて欲しいです

私はこの順序で良いと思っていますが、あえて新しい案を出すとすれば文字コード順とかですかね…

## コントリビューター (文字コード順)
- Aさん ([GitHub](https://github.com/), [Twitter](https://twitter.com/))
- Bさん
- Cさん ([GitHub](https://github.com/))
- あさん

こうすれば Discord と Twitter と GitHub と… みたいなこともできますし。

**Comment by kmikage** [comment]
あぁ、なるほどー
これはアリかも知れません。
お手数ですが、こちら修正お願いしてよいですか？

**Comment by pklion** [comment]
承知しました。
ちょっと忙しいので明後日ごろまでかかるかもしれませんが、PRしておきますね。

**Comment by kmikage** [comment]
@pklion 更新しましたっ

**Comment by pklion** [comment]
ありがとうございます！
Close します～
